apiVersion: apps/v1
kind: Deployment
metadata:
  name: okte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okte
  template:
    metadata:
      labels:
        app: okte
    spec:
      containers:
      - image: okteto.dev/myu:latest
        name: okte
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "66efbbea-2011-4e1d-994a-ac9941864505"
        - name: Vless_Path
          value: "/fgh76u4wrgjyu"
        - name: Vmess_UUID
          value: "66efbbea-2011-4e1d-994a-ac9941864505"
        - name: Vmess_Path
          value: "/fdbjui75u56ehtd"
        - name: Share_Path
          value: "/v2link"
